### ISSUE TITLE
bug in DQMC?

### ISSUE THREAD

**Issue by hungpham2017** [sanshar/Dice#7]
Hello,

I couldn't compile DQMC part of the code because [this line](https://github.com/sanshar/Dice/blob/master/DQMC/DQMCWalker.cpp#L386)

`cout << oneBodyOperator << endl;`

I could compile the code with this change:

`cout << expOneBodyOperator << endl;`

Is this change correct? Thank you

**Comment by xubwa** [comment]
Sorry, that line is just a debug line I forgot to clean up, you may just delete it and I'll fix that soon.
Xubo
________________________________
From: Hung Pham ***@***.***>
Sent: Friday, September 30, 2022 4:20:16 PM
To: sanshar/Dice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sanshar/Dice] bug in DQMC? (Issue #7)


Hello,

I couldn't compile DQMC part of the code because this line<https://github.com/sanshar/Dice/blob/master/DQMC/DQMCWalker.cpp#L386>

cout << oneBodyOperator << endl;

I could compile the code with this change:

cout << expOneBodyOperator << endl;

Is this change correct? Thank you

**Comment by hungpham2017** [comment]
thanks.
